sudo: false

language: node_js

node_js:
  - "lts/*"

install:
  - npm install

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - NODE_ENV=CI

jobs:
  include:
    - stage: test
      script: 
        - npm run test-coverage-ci
        - docker build .
    - stage: deploy
      if: branch = master
      script:
        - chmod +x ./deploy-ci.sh
        - ./deploy-ci.sh
      skip_cleanup: true
